### ISSUE TITLE
Clean import/export of Mio's City Outfit causes game freezes

### ISSUE THREAD

**Issue by NepposTheNose** [ScanMountGoat/xenoblade_blender#51] opened 2024-09-05 06:59 UTC
Original **.wimdo** file size : **75 KB** | Original **.wismt** file size : **1.390 KB**
Exported **.wimdo** file size: **81 KB** | Exported **.wismt** file size: **9.916 KB**

**Importing ch04002410.wimdo with the following options:**
- Game Version: Xenoblade 3
- ☐ Pack Images
- 🗹 Import All Meshes
- 🗹 Import Outlines

**Leaving the import completely unedited and exporting it with the following options:**
- Original Wimdo: D:\NewInstalls\A EMULATION\xbtool_040623\XC3 Basegame\chr\ch\ch04002410.wimdo
- 🗹 Create _speff mes...
- ☐ Export Images

**Causes a slight chance to freeze when opening/navigating the menu while wearing Mio's City outfit** (with the Rebalance mod).
Sometimes Sudachi remains responsive, and can be closed by pressing F5.
Other times GPU activity spikes to 100%, and the emulator must be closed using the Task Manager.

Maybe Mio's long hair option doesn't play nice with this outfit, but I have it disabled anyway.
**Mio's** exported **City Outfit** freezes the game regardless of Blender settings, I just put them here to have something concrete.
Editing **Noah's City Outfit** (ch04002310.wimdo) did not cause this issue in my testing. I did not specify an Original Wimdo path.
[Mio City Broken Export.zip](https://github.com/user-attachments/files/16885234/Mio.City.Broken.Export.zip)

**Comment by ScanMountGoat** [comment] 2024-09-05 13:43
Does this issue still happen in Ryujinx? Yuzu and Yuzu clones are known to have some issues compared to Ryujinx and actual hardware.

**Comment by NepposTheNose** [comment] 2024-09-05 19:01
> Does this issue still happen in Ryujinx? Yuzu and Yuzu clones are known to have some issues compared to Ryujinx and actual hardware.

Yep! Just set up Ryujinx, and it didn't even take 2 minutes of navigating the menu while wearing Mio's exported City outfit, for the game to outright crash.

**Comment by ScanMountGoat** [comment] 2024-09-05 21:21
Does it crash if you don't modify the files for Mio with xenoblade_blender? I'm not seeing any crashes on Ryujinx when replacing Mio's outfit (ch01021013) with her city outfit (ch04002410) exported from Blender. What file are you replacing?

**Comment by NepposTheNose** [comment] 2024-09-05 21:33
I am replacing ch04002410 with itself, imported and exported without editing anything. I then have Mio wear the city outfit using Lemon Fry's Ultimate XC3 Rebalance Mod, which adds a new costume slot using ch04002410.

The game only crashes after I replace the original ch04002410 with its exported, theoretically-unchanged-but-not-really self.

I could try doing a model swap with a vanilla outfit, and see if the game still freezes/crashes then

**Comment by NepposTheNose** [comment] 2024-09-05 21:47
I have tried to replace Mio's Thaumaturge outfit (ch01021143) and the game froze the moment I switched to her character page in the menu

**Comment by ScanMountGoat** [comment] 2024-09-05 22:18
Does the extra costume slot for ch04002410 work without modifying the files? It could be an issue with the rebalance mod.

**Comment by NepposTheNose** [comment] 2024-09-06 06:01
> Does the extra costume slot for ch04002410 work without modifying the files? It could be an issue with the rebalance mod.

Yep. In NG+ I was playing **all the way to Pentelas** without a single freeze or crash, wearing Mio's City Outfit for ~80% of that.

I was trying to fix playable City N's and City M's facial animations, to put up the fix on Gamebanana later.
My tweak to Noah's model worked fine, but it is Mio's City outfit being run through Xenoblade_Blender that freezes the game.

To make sure I wasn't making a mistake, I imported and exported the model without making any changes. Same result.
**As long as I don't put the outfit through Xenoblade_Blender, it works consistently.**

I did think it might've been a problem with the Rebalance mod!
But given that the game also freezes when I replace her Thaumaturge mod, I think it's a problem with the Blender process.
The freezes/crashes occur on both **Sudachi** and **Ryujinx**. My Switch is dead, so I can't check on real hardware, sorry to say.

Do your exports also produce .wismt filesizes 7x larger than the original?

**Comment by ScanMountGoat** [comment] 2024-09-06 13:38
That helps narrow it down. Thanks. I'll see if I can reproduce this on some of Mio's outfit models in Ryujinx.

> Do your exports also produce .wismt filesizes 7x larger than the original?

That's normal. Exports embed all the external textures files. This makes the mod not conflict with any other models but increases the file size. Some exports for other games might even be smaller due to not using external textures and not including unused vertex data.

**Comment by ScanMountGoat** [comment] 2024-09-09 14:15
I'm able to reproduce this now on my end with either a freeze or crash when exporting ch04002410 over ch01021013 (base outfit). I'll try and look into what's causing the issues in game. You mentioned that the unmodified in game model works, so this is probably some sort of xenoblade_blender bug.

You can try deleting anything above her neck for now and see if that helps. It seems to fix the crashing for me. Playable characters have a separate file for their heads and hair, so this should look the same in game.
![image](https://github.com/user-attachments/assets/321ee95c-a53b-4590-83cc-0c7caf04d1f5)

**Comment by NepposTheNose** [comment] 2024-09-11 01:26
> You can try deleting anything above her neck for now and see if that helps. Playable characters have a separate file for their heads and hair, so this should look the same in game.)

Yeah, it would actually look better! That was the first thing I tried to fix her facial animations.

Sadly deleting the head & hair caused the game to freeze 100% during Ouroboros Chain Orders, so it's not a perfect solution.
Maybe I did something wrong though, I just started with Blender last week.

But hey, thanks for looking into this!

**Comment by ScanMountGoat** [comment] 2024-09-11 01:36
> Sadly deleting the head & hair caused the game to freeze 100% during Ouroboros Chain Orders, so it's not a perfect solution.

I'll see if I can reproduce this on my end.

**Comment by ScanMountGoat** [comment] 2024-09-11 13:47
It crashes for me when Mio transforms back from orobouros form in the chain order. This may be related to the issues with the meshes used for transition effects that also are used for the character menu transitions. I'll try and narrow this down later.

**Comment by NepposTheNose** [comment] 2024-09-24 08:29
I'm back with some files that **might be useful for troubleshooting the issue**. I've attached them to this message.



**There are two model swaps. One broken, the other functional.**

The first replaces Sena with Shania, with her facial animations intact. She can move her eyes, brows and mouth.
The second replaces Lanz with Guernica, with his facial animations intact. He can move his mouth, his eyes are covered by his mask.



**Same issue as with Mio's City outfit, but only with Shania:**

The Shania swap works wonderfully until I execute an Ouroboros Order. When "Senia" rematerializes, the game freezes.
Fascinatingly, the Guernica swap does not have the same issue. "Guerniclanz" can rematerialize without freezing the game.



**The following files have been replaced:**

_SHANIA SENA SWAP_
- ch01061010.chr (replaced with Shania's original ch04001410.chr, no idea what this does but I figured I might as well)
- ch01061011.wimdo/wismt (replaced with Shania's facial meshes only)
- ch01061012.wimdo/wismt (replaced with Shania's hair meshes only)
- ch01061013.wimdo/wismt (replaced with Shania's body, eyepatch and hairclip only)

_GUERNICA LANZ SWAP_
- ch01051010.chr (replaced with Guernica's original ch04000210.chr, again, no idea what this does)
- ch01051011.wimdo/wismt (replaced with Guernica's original whole mesh)
- ch01051012.wimdo/wismt (replaced with Guernica's body, hair and mask — no face)
- ch01051013.wimdo/wismt (replaced with Guernica's body, hair and mask — no face)



[Shania Sena Swap 4 Testing Purposez.zip](https://github.com/user-attachments/files/17110555/Shania.Sena.Swap.4.Testing.Purposez.zip)
[Shania Sena Swap 5 Testing Purposez.zip](https://github.com/user-attachments/files/17110910/Shania.Sena.Swap.5.Testing.Purposez.zip)
[Guernica Lanz Swap 4 Testing Purposez.zip](https://github.com/user-attachments/files/17111034/Guernica.Lanz.Swap.4.Testing.Purposez.zip)
[Guernica Lanz Swap 5 Testing Purposez.zip](https://github.com/user-attachments/files/17111047/Guernica.Lanz.Swap.5.Testing.Purposez.zip)

**Comment by ScanMountGoat** [comment] 2024-09-24 14:20
I'm able to reproduce the issue on my end with those files. I've also noticed that the same models that crash when exiting an ourobouros chain order also crash when entering a rest spot. The rest spot is much easier for me to use during testing. I'll diff the files and see if I can narrow this down.

**Comment by ScanMountGoat** [comment] 2024-09-24 20:26
This appears to be fixed on the latest commit. I tested rest spots and ouroboros chain orders for Mio's city outfit as well as Shania over Sena and a few others. The issue with exporting a complete model over an outfit that's just a body is probably unrelated. Deleting the duplicate head and hair meshes before exporting works properly now. If you encounter any similar problems in the future, please open a new issue.

I plan on having a new release out by the end of the week with some additional changes not related to this issue.

**Closed by ScanMountGoat** 2024-09-24 20:26 UTC
Labels: bug
